server:
  port: 8080
  servlet:
    session:
      timeout: 10080

spring:
  application:
    name: spring-security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: oweikj